# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: main.yml
omnia_metadata_file: "/opt/omnia/.data/oim_metadata.yml"

# Usage: firewall_settings.yml
oim_os_repo_fail_msg: |
  Failed to install firewalld. This could be due to the OS repository not being configured on OIM.
  Please configure the OS repository on OIM and rerun the playbook.
xcat_firewall_ports:
  - "3001/tcp"
  - "3001/udp"
  - "3002/tcp"
  - "3002/udp"
  - "7/udp"
  - "22/tcp"
  - "22/udp"
  - "873/tcp"
  - "873/udp"
  - "67/udp"
  - "68/tcp"
  - "69/tcp"
  - "69/udp"
  - "80/tcp"
  - "80/udp"
  - "111/udp"
  - "514/tcp"
  - "514/udp"
  - "782/tcp"
  - "2049/tcp"
  - "2049/udp"
  - "4011/tcp"
  - "623/tcp"
  - "623/udp"
  - "161/tcp"
  - "161/udp"
  - "162/tcp"
  - "162/udp"
  - "2240/tcp"
  - "5432/tcp"
  - "5432/udp"

pcs_firewall_ports:
  - "5404-5405/udp"
  - "3121/tcp"
  - "2224/tcp"
  - "2222/tcp"

pcs_firewall_services:
  - "http"
  - "https"

# Usage:
prepare_oim_completion_msg: |
  The playbook prepare_oim.yml has completed successfully. To create the offline repositories and
  registry for the cluster nodes, please execute the playbook local_repo/local_repo.yml as the next step.

# podman_login.yml
login_cmd: "podman login -u {{ docker_username }} -p {{ docker_password }}"
retry_count: "5"
delay_time: "10"
podman_login_fail_msg: "Podman login failed. Please ensure the podman login credentials in the input/omnia_config_credentials.yml are valid.
If they are, this error can occur due to a pull limit issue or multiple requests. Please try running the playbook again after waiting for a while."
